apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: wshoto-demo-order-build-task
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
      - name: wshoto-demo-order
        type: git
  params:
    - name: pathToContext
      default: .
    - name: pathToDockerFile
      default: Dockerfile
    - name: imageUrl
    - name: imageTag
      default: v1
    - name: profile
  workspaces:
    - name: output
      mountPath: /workspace
  steps:
    - name: maven
      image: maven:3.6.3-openjdk-8-slim
      workingDir: /workspace/wshoto-demo-order
      command:
        - mvn
      args:
        - clean
        - package
        - -U
        - -DskipTests
      volumeMounts:
        - mountPath: /root/.m2/settings.xml
          name: config
          subPath: settings.xml
        - name: m2
          mountPath: /root/.m2
    - name: kustomize-edit
      image: wshoto.tencentcloudcr.com/qwgj/kustomize:latest
      workingDir: /workspace/wshoto-demo-order/.deploy/overlays/$(params.profile)
      command:
        - kustomize
      args:
        - edit
        - set
        - image
        - $(params.imageUrl):$(params.imageTag)
    - name: build-and-push
      image: wshoto.tencentcloudcr.com/qwgj/kaniko-executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(params.imageUrl):$(params.imageTag)
        - --context=/workspace/wshoto-demo-order/wshoto-demo-order-server/wshoto-demo-order-server-bootstrap/$(params.pathToContext)
  volumes:
    - name: config
      configMap:
        defaultMode: 384
        name: maven-config
    - name: m2
      hostPath:
        path: /home/docker/.m2
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: wshoto-demo-order-deploy-task
  namespace: tekton-pipelines
spec:
  params:
    - name: profile
  workspaces:
    - name: src
      mountPath: /workspace
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: [ "kubectl" ]
      args:
        - "apply"
        - "-k"
        - "/workspace/wshoto-demo-order/.deploy/overlays/$(params.profile)"
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: wshoto-demo-order-pipeline
  namespace: tekton-pipelines
spec:
  resources:
    - name: wshoto-demo-order
      type: git
  params:
    - name: pathToContext
      default: .
    - name: imageUrl
    - name: imageTag
    - name: profile
  workspaces:
    - name: wshoto-demo-order-share-data
  tasks:
    - name: wshoto-demo-order-build-task
      taskRef:
        name: wshoto-demo-order-build-task
      workspaces:
        - name: output
          workspace: wshoto-demo-order-share-data
      params:
        - name: pathToContext
          value: "$(params.pathToContext)"
        - name: imageUrl
          value: "$(params.imageUrl)"
        - name: imageTag
          value: "$(params.imageTag)"
        - name: profile
            value: "$(params.profile)"
      resources:
        inputs:
          - name: wshoto-demo-order
            resource: wshoto-demo-order
    - name: wshoto-demo-order-deploy-task
      runAfter:
        - wshoto-demo-order-build-task
      taskRef:
        name: wshoto-demo-order-deploy-task
      workspaces:
        - name: src
          workspace: wshoto-demo-order-share-data
      params:
        - name: profile
          value: "$(params.profile)"