apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: wshoto-demo-order-generic-pr-
  name: wshoto-demo-order-generic-pipeline-run
  namespace: tekton-pipelines
spec:
  serviceAccountName: pipeline-account
  pipelineRef:
    name: wshoto-demo-order-pipeline
  workspaces:
    - name: wshoto-demo-order-share-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
      # persistentVolumeClaim:
      #   claimName: shared-data-storage
  resources:
    - name: wshoto-demo-order
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://gitee.com/wshoto/wshoto-demo-order.git
          - name: revision
            value: v2
      # resourceRef:
      #   name: wshoto-demo-order-source
  params:
    - name: imageUrl
      value: wshoto.tencentcloudcr.com/qwgj/wshoto-demo-order
    - name: imageTag
      value: v2
    - name: pathToYamlFile
      value: deployment-test.yaml