apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: wshoto-demo-order
    spring.cloud.kubernetes.config: "true"
  name: wshoto-demo-order
  namespace: demo
data:
  application.yml: |-
    server:
      tomcat:
        accept-count: 2000
        max-connections: 40960
        threads:
          max: 2000
      port: 7371
      servlet:
        encoding:
          charset: UTF-8
          force: true
          enabled: true
    spring:
      http:
        encoding:
          uri-encoding: UTF-8
      rest:
        connection-timeout: 5000
        read-timeout: 5000
      cache-manager:
        entry-ttl: 8
      redis:
        host: 81.68.66.100
        port: 6379
        password: wshoto@2020
      h2:
        console:
          path: /h2
          enabled: true
          settings:
            web-allow-others: true
      datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:demodb?stringtype=unspecified&useUnicode=true&characterEncoding=UTF-8
        username: sa
        password: wshoto@2020
        schema: classpath:/db/schema.sql
        data: classpath:/db/data.sql
        druid:
          initialSize: 20
          minIdle: 20
          maxActive: 100
          maxWait: 10000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          validationQuery: select 1
          validationQueryTimeout: 1
          keepAlive: true
          removeAbandoned: true
          removeAbandonedTimeout: 80
          logAbandoned: true
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 200
    mybatis-plus:
      mapper-locations: classpath:/mapper/**/*Mapper.xml
      global-config:
        banner: false
        db-config:
          id-type: assign_id
          logic-delete-field: deleted
          logic-delete-value: 1
          logic-not-delete-value: 0
      configuration:
        cache-enabled: true
        default-executor-type: reuse
      entry-ttl: 8
    wshoto:
      audit-log:
        enable: true