apiVersion: v1
kind: Secret
metadata:
  name: gitee-secret
type: Opaque
stringData:
  secretToken: "1234567"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitee-auth
  annotations:
    tekton.dev/git-0: http://gitee.com
type: kubernetes.io/basic-auth
stringData:
  username: dxk19911212
  password: dxk?19911212