apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitee-listener
spec:
  serviceAccountName: tekton-triggers-gitee-sa
  triggers:
    - name: gitee-push-events-trigger
      interceptors:
        - webhook:
            header:
              - name: Foo-Trig-Header1
                value: string-value
              - name: Foo-Trig-Header2
                value:
                  - array-val1
                  - array-val2
      bindings:
        - ref: gitee-push-binding  # TriggerBinding 对象
      template:
        ref: gitee-echo-template  # TriggerTemplate 对象