apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitee-push-binding
spec:
  params:
    - name: gitrevision
      value: $(head_commit.id)
    - name: gitrepositoryurl
      value: $(repository.url)