apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitee-echo-template
spec:
  params:  # 定义参数，和 TriggerBinding 中的保持一致
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun  # 定义 TaskRun 模板
      metadata:
        generateName: gitee-run-  # TaskRun 名称前缀
      spec:
        serviceAccountName: tekton-triggers-example-sa
        taskSpec:  # Task 任务声明
          inputs:
            resources:  # 定义一个名为 source 的 git 输入资源
              - name: source
                type: git
          steps:
            - name: show-path
              image: ubuntu  # 定义一个执行步骤，列出代码目录结构
              script: |
                #! /bin/bash
                ls -la $(inputs.resources.source.path)
        inputs:  # 声明具体的输入资源参数
          resources:
            - name: source  # 和 Task 中的资源名保持一直
              resourceSpec:  # 资源声明
                type: git
                params:
                  - name: revision
                    value: $(params.gitrevision)  # 读取参数值
                  - name: url
                    value: $(params.gitrepositoryurl)