apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
spec:
  routes:
    - match:
        http:
          pathPrefix: /app
      destination:
        service: wshoto-demo-app
    - match:
        http:
          pathPrefix: /order
      destination:
        service: wshoto-demo-order
    - match:
        http:
          pathPrefix: /user
      destination:
        service: wshoto-demo-user
