apiVersion: v1
kind: Secret
metadata:
  name: gitee-secret
type: Opaque
stringData:
  # 校验token
  secretToken: "1234567"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitee-auth
  annotations:
    tekton.dev/git-0: https://gitee.com
type: kubernetes.io/basic-auth
stringData:
  # git仓库账号密码
  username: dxk19911212
  password: dxk?19911212