apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacos-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-pv-claim
  namespace: nacos
spec:
  storageClassName: manual2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

