apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-config
  namespace: tekton-pipelines
data:
  settings.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
        <servers>
            <server>
                <id>central</id>
                <username>admin</username>
                <password>AP9zL7QhRfvgwyPwDYAJmSMZ98G</password>
            </server>
            <server>
                <id>snapshots</id>
                <username>admin</username>
                <password>AP9zL7QhRfvgwyPwDYAJmSMZ98G</password>
            </server>
            <server>
                <id>artifactory</id>
                <username>admin</username>
                <password>AP9zL7QhRfvgwyPwDYAJmSMZ98G</password>
            </server>
        </servers>

        <mirrors>
            <mirror>
                <id>artifactory</id>
                <mirrorOf>*</mirrorOf>
                <name>Artifactory</name>
                <url>http://192.168.2.57:8081/artifactory/public/</url>
            </mirror>
        </mirrors>

        <profiles>
            <profile>
                <id>artifactory</id>
                <repositories>
                    <repository>
                        <id>central</id>
                        <url>http://192.168.2.57:8081/artifactory/release/</url>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </repository>
                    <repository>
                        <id>snapshots</id>
                        <url>http://192.168.2.57:8081/artifactory/snapshot/</url>
                        <releases>
                            <enabled>false</enabled>
                        </releases>
                    </repository>
                </repositories>
                <pluginRepositories>
                    <pluginRepository>
                        <id>central</id>
                        <url>http://192.168.2.57:8081/artifactory/plugins-release/</url>
                        <snapshots>
                            <enabled>false</enabled>
                        </snapshots>
                    </pluginRepository>
                    <pluginRepository>
                        <id>snapshots</id>
                        <url>http://192.168.2.57:8081/artifactory/plugins-snapshot/</url>
                        <releases>
                            <enabled>false</enabled>
                        </releases>
                    </pluginRepository>
                </pluginRepositories>
            </profile>
        </profiles>
        <activeProfiles>
            <activeProfile>artifactory</activeProfile>
        </activeProfiles>
    </settings>
