apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo-route-redirect
  namespace: no-injection
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo1.wshoto.com`)
      kind: Rule
      services:
        - name: wshoto-demo-user
          port: 7371
      middlewares:
        - name: secured
    - match: Host(`demo2.wshoto.com`)
      kind: Rule
      services:
        - name: wshoto-demo-user
          port: 7371
      middlewares:
        - name: secured
  tls:
    secretName: demo-ssl-secret