apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo-route
  namespace: no-injection
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`demo.wshoto.com`) && PathPrefix(`/no-injection`)
      kind: Rule
      services:
      - name: wshoto-demo-user
        port: 7371
      middlewares:
      - name: demo-redirectscheme